name: Ubuntu Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Run Ubuntu container with SSH
      run: |
        docker run --cpus="4" --memory="8g" --rm -v $(pwd):/workspace -w /workspace -p 2222:22 -d --name my_ubuntu_container ubuntu:latest bash -c "
          apt-get update &&
          apt-get install -y openssh-server curl &&
          echo 'root:password' | chpasswd &&
          service ssh start &&
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&
          apt-get install -y nodejs &&
          tail -f /dev/null
        "

    - name: Wait for SSH to be ready
      run: |
        while ! nc -z localhost 2222; do sleep 1; done

    - name: SSH into the container and check Node.js
      run: |
        sshpass -p password ssh -o StrictHostKeyChecking=no root@localhost -p 2222 'node -v'

    - name: Stop and remove container
      if: always()
      run: docker stop my_ubuntu_container
